[build]
  command = "npm run build"
  publish = "client/dist"

[dev]
  command = "npm run dev"
  functions = "./functions"

  [[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/data/*"
  to = "/.netlify/functions/data"
  status = 200
