[build]
  command = "npm install && npm run colect:data && npm run serve"
  functions = "./functions"

[dev]
  functions = "./functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/data/*"
  to = "/.netlify/functions/weather"
  status = 200
